// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_ilg9h3OEdPgUjhllwlnJ6W8X39Db2M4',
    appId: '1:908990332611:web:fa111643eb9a107c65ac76',
    messagingSenderId: '908990332611',
    projectId: 'nexivo-financecalc',
    authDomain: 'nexivo-financecalc.firebaseapp.com',
    storageBucket: 'nexivo-financecalc.firebasestorage.app',
    measurementId: 'G-TCQWRXWVL9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQmhQ-UTENTvBkSDfV3ad8o0w242OCyrE',
    appId: '1:908990332611:android:8c36e6e5fcfa566765ac76',
    messagingSenderId: '908990332611',
    projectId: 'nexivo-financecalc',
    storageBucket: 'nexivo-financecalc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtveurDjB151C0-7OBRsDYCu9PWu22elM',
    appId: '1:908990332611:ios:ba755a33522fe93365ac76',
    messagingSenderId: '908990332611',
    projectId: 'nexivo-financecalc',
    storageBucket: 'nexivo-financecalc.firebasestorage.app',
    iosBundleId: 'com.nexivo.financecalc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtveurDjB151C0-7OBRsDYCu9PWu22elM',
    appId: '1:908990332611:ios:bb5f9b30a0228a8865ac76',
    messagingSenderId: '908990332611',
    projectId: 'nexivo-financecalc',
    storageBucket: 'nexivo-financecalc.firebasestorage.app',
    iosBundleId: 'com.example.emiCalculator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_ilg9h3OEdPgUjhllwlnJ6W8X39Db2M4',
    appId: '1:908990332611:web:2879b78877c5db4c65ac76',
    messagingSenderId: '908990332611',
    projectId: 'nexivo-financecalc',
    authDomain: 'nexivo-financecalc.firebaseapp.com',
    storageBucket: 'nexivo-financecalc.firebasestorage.app',
    measurementId: 'G-C5X0NWD6RH',
  );
}
